#!/bin/bash


sudo apt update && sudo apt upgrade -y
##########################
####Install KDE###########
##########################
#sudo apt install kde-standard


##########################
####Dock Customization####
##########################
#sudo apt install dconf-editor
